os:
  - linux

language: php

php:
  - '7.3'

before_script:
  - cp .env.travis .env
  - sudo mysql -e 'CREATE DATABASE homestead;'
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate --no-interaction -vvv

script:
  - vendor/bin/phpunit
